security:
    enable_authenticator_manager: true
    encoders:
        App\Infrastructure\Persistence\Doctrine\Entity\User: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_admin_provider:
            id: App\Infrastructure\Security\AdminUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login: ~
            logout:
                path: logout
            custom_authenticators:
                - App\Infrastructure\Security\AdminFormAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Allow unauthenticated users to access the login form
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
