# Docker compose file
version: "3.6"

services: 
    http:
        container_name: apache_php8
        build: ./docker
        ports: 
            - "80:80"
        volumes: 
            - .:/var/www
    mysql:
        container_name: database_mysql
        image: mysql:5.7
        ports:
        -   "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: container_admin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
        links:
            - mysql

