name: Symfony 5 CI test

on:
  push:
    branches:
      - develop
      - main

jobs:
  symfony:
    name: Symfony 5.2 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306

    strategy:
      fail-fast: true
      matrix:
        php-versions:
          - 8.0
        node-version:
          - 14.7

    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Setup webpack encore with yarn
      - name: install Yarn
        run: npm install -g yarn

      - name: Install depedencies
        run: yarn install

      - name: Build assets
        run: yarn encore production

      # composer
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install depedencies
        run: composer install

      # starting mysql server
      - name: start mysql
        run : sudo /etc/init.d/mysql start

      # init database
      - name: create database
        run: |
          php bin/console doctrine:database:drop --if-exists --force
          php bin/console doctrine:database:create
          php bin/console doctrine:schema:update --force
          php bin/console doctrine:fixtures:load --no-interaction

      # running test
      - name: run functional tests
        run: php bin/phpunit

      # running code quality tools
      - name: run phpstan
        run: ./vendor/bin/phpstan analyse src

      - name: fix phpcs errors
        run: ./vendor/bin/phpcbf src

      - name: run php code sniffer
        run: ./vendor/bin/phpcs src





