name: Symfony 5 CI test
on:
  push:
    branches:
      - develop
      - main

jobs:
  symfony:
    name: Symfony 5.2 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions:
          - 8.0
    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php-versions }}

      # composer
      - name: Validate composer.json and composer.lock
        run: composer validate


